/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

public class App {
    public String getGreeting() {
        return "Welcome to Gradle Java App application";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	System.out.println("Welcome to Gradle Tool");
	try {

	Class.forName("com.mysql.cj.jdbc.Driver");
	System.out.println("Driver Loaded....");
	}catch(Exception e) {

	}

    }
}
