/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MySimpleGradleApp;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		System.out.println("This is My Simple Gradle Project");
	}
}
