/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Library {
    
	public static void main(String[] args) {
		SpringApplication.run(Library.class, args);
		System.err.println("Server running on port number 8080");
	}
}
